project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - research.qmd
    - teaching.qmd
    - econometrics_undergrad.qmd
    - econometrics_graduate.qmd
    - cv.qmd
  resources:
    - images/
    - files/

website:
  title: "Kei Ikegami"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: cv.qmd

format:
  html:
    css: styles.css
    toc: false