---
title: "計量経済学(学部)"
---


基本的な計量経済学のツールと因果推論のテクについて学ぶ授業です。計量経済学を学ぶモチベーションを説得的に言語化できている文章を読んだことがなかったので、その辺りに注意してlecture noteを作成しています。

## 講義ノートなど

1. Lecture 1 — [Notes](/files/teaching/econometrics_undergrad/lec1/lecture1_revised.html) · [Source](/files/teaching/econometrics_undergrad/lec1/lecture1_source.zip) · [Slides](/files/teaching/econometrics_undergrad/lec1/lecture1_slide.pptx)

    計量経済学は、あなたの渾身のデータ分析に対して嫌なことを言ってくる奴を黙らせるための方法論を提示してくれます。
    計量経済学を学ぶと、会社や組織でデータを使った議論を展開するときに、議論に負けにくくなります。
    データサイエンス的な仕事に興味のある人はみんな学んでくれるとこちらも話がしやすくなるので、文系理系問わず一緒に勉強しましょう。

2. Lecture 2 — [Notes](/files/teaching/econometrics_undergrad/lec2/lecture2_revised.html) · [Source](/files/teaching/econometrics_undergrad/lec2/lecture2_source.zip) · [Slides](/files/teaching/econometrics_undergrad/lec2/lecture2_slide.pptx)

    計量経済学の基本的な概念として、識別、推定、推論があります。これらについて学びます。
    計量経済学の目的は経済現象のシミュレーションをすることにあり、それを実現するための3つのステップが識別、推定、推論です。
    給料と学歴の関係を例にとって、計量経済学的な議論の流れを掴みましょう。

3. Lecture 3 — [Notes](/files/teaching/econometrics_undergrad/lec3/lecture3_revised.html) · [Source](/files/teaching/econometrics_undergrad/lec3/lecture3_source.zip) · [Slides](/files/teaching/econometrics_undergrad/lec3/lecture3_slide.pptx)

    計量経済学の全てはOLSにあります。今回はその中でも最も基本的な単回帰について学びます。Yという変数とXという変数の関係性を見る道具です。
    実験ができる状況ならこれで大体の問題は解決します。

4. Lecture 4 — [Notes](/files/teaching/econometrics_undergrad/lec4/lecture4_revised.html) · [Source](/files/teaching/econometrics_undergrad/lec4/lecture4_source.zip) · [Slides](/files/teaching/econometrics_undergrad/lec4/lecture4_slide.pptx)

    まだOLSについて学ぶことがあります。今回は特に、回帰分析が意味のある分析になる状況について考えます。
    逆にいうと、回帰分析は特定の状況以外ではせっかくやっても経済学者に文句を言われて無駄になってしまいます。それを避けられるようになりましょう。
    ついでに論文に出てくる回帰表などを読めるようになりましょう。

5. Lecture 5 — [Notes](/files/teaching/econometrics_undergrad/lec5/lecture5_revised.html) · [Source](/files/teaching/econometrics_undergrad/lec5/lecture5_source.zip) · [Slides](/files/teaching/econometrics_undergrad/lec5/lecture5_slide.pptx)

    まだまだOLSについて学ぶことがあります。たくさんの変数がある回帰分析をやっていきます。Yという変数を $X_1,X_2$ という二つの変数で説明できるかを見ることができます。なぜそれが嬉しいのか？それは、ある変数が同じ人同士を比べたら、別の変数についての回帰係数に「意味」が宿りうるからです。
 
6. Lecture 6 — [Notes](/files/teaching/econometrics_undergrad/lec6/lecture6_revised.html) · [Source](/files/teaching/econometrics_undergrad/lec6/lecture6_source.zip) · [Slides](/files/teaching/econometrics_undergrad/lec6/lecture6_slide.pptx)

    OLSを使うと色々なことができるようになります。例えば因果推論とか。今回はOLSの応用をしていく上での基本的なツールを導入します。
    さらに、OLSだけで論文も書けちゃいます。つまりもう君たちは学術的な貢献をする準備が整っています。OLSだけで成り立っている論文として、偽の履歴書を大量に作成し、名前だけ白人っぽいやつと黒人っぽいやつに変えた2バージョンを用意して、企業に送りつけまくって差別が起きてそうかを検証した論文などを紹介します。

7. Lecture 7 — [Notes](/files/teaching/econometrics_undergrad/lec7/lecture7_revised.html) · [Source](/files/teaching/econometrics_undergrad/lec7/lecture7_source.zip) · [Slides](/files/teaching/econometrics_undergrad/lec7/lecture7_slide.pptx)

    DiD、差分の差法について学びます。これを学ぶと、あなたが会社でとあるマーケティング施策の効果を図りましたという報告を聞いたときに、それが前後比較や施策をしたグループとしなかったグループの単純な比較だけで結論づけていたら、ドヤ顔でそこに隠れている問題を指摘することができるようになります。

8. Lecture 8 — [Notes](/files/teaching/econometrics_undergrad/lec8/lecture8_revised.html) · [Source](/files/teaching/econometrics_undergrad/lec8/lecture8_source.zip) · [Slides](/files/teaching/econometrics_undergrad/lec8/lecture8_slide.pptx)

    固定効果モデルについて学びます。これを学ぶと、データをパッと見たときに、肥料投入量が多い農家ほど農作物の収穫量が低いというパターンがあっても、肥料投入量が生産増につながっているかもしれないと指摘できるようになります。また、どういうデータがあるとどういう分析ができるのか、という肌かんを得ることができます。

9. Lecture 9 — [Notes](/files/teaching/econometrics_undergrad/lec9/lecture9_revised.html) · [Source](/files/teaching/econometrics_undergrad/lec9/lecture9_source.zip) · [Slides](/files/teaching/econometrics_undergrad/lec9/lecture9_slide.pptx)

    操作変数法について学びます。YとXの関係性を考えるときに、Xに影響するが、Xを通さずにはYに影響しない変数Zをを使って、Yのブレが実際どれだけXのブレだけから生まれているのかを見つける手法です。これを学ぶと、この世に出てくる大体すべての社会的なデータの分析結果に対して、文句を言うことができるようになります。また、その解決策を提示できるようになるかもしれません。

10. Lecture 10 — [Notes](/files/teaching/econometrics_undergrad/lec10/lecture10_revised.html) · [Source](/files/teaching/econometrics_undergrad/lec10/lecture10_source.zip) · [Slides](/files/teaching/econometrics_undergrad/lec10/lecture10_slide.pptx)

    RDD、不連続回帰について学びます。操作変数の見つけ方の一つとでも思ってください。何か非連続なカットオフの存在する制度を見つけたら経済学者までご一報を。論文を書くことができます。

