---
title: "計量経済学（大学院）"
---


大学院レベルの計量経済学の授業です。ちょっとだけ厳密に確率変数とか条件付き期待値とかを導入してから、GMM,MLE,MSMなどの構造推定で用いられる推定手法とその統計的性質について解説します。
参考にしているのは、

- 舟木『確率論』
- Kengo Katoの測度論的確率論のlecture note
- Tim Christensenのeconometricsのlecture ntoe

です。

わからないことが出たらメモって後でChat gptとかに聞きましょう。Chat gptにたくさん聞けることを前提にそこそこのスピードで進める予定です。とにかくわからないことの小さい具体例を作ってもらうのがおすすめです。

練習問題的なものは随時アップしていきます。期末試験はペーパー試験でそこから数問解いてもらいます。

授業の最後数回は、機械学習とかと接続されているもっとモダンな計量経済学のペーパーの輪読を一人一本ずつやる予定です。候補は

- "Recursive partitioning for heterogeneous causal effects", Susan Athey Athey and Guido Imbens, 2016, PNAS
- "Estimation and Inference of Heterogeneous Treatment Effects using Random Forests", Stefan Wager and Susan Athey, 2018, JASA
- "Prediction Policy Problems", Kleinberg et al., 2015, AER
- "Inference on Treatment Effects after Selection among High-Dimensional Controls", Belloni et al., 2014
- "Double/debiased machine learning for treatment and structural parameters", Chernozhukov et al., 2018, Econometrics Journal
- "Who Should Be Treated? Empirical Welfare Maximization Methods for Treatment Choice", Toru Kitagawa and Aleksey Tetenov, 2018

## 講義ノート

1. Lecture 1 — [Notes](/files/teaching/econometrics_graduate/lecture1/lecture1.html)

2. Lecture 2 — [Notes](/files/teaching/econometrics_graduate/lecture2/lecture2.html)

3. Lecture 3 — [Notes](/files/teaching/econometrics_graduate/lecture3/lecture3.html)

4. Lecture 4 — [Notes](/files/teaching/econometrics_graduate/lecture4/lecture4.html)

5. Lecture 5 — [Notes](/files/teaching/econometrics_graduate/lecture5/lecture5.html)

6. Lecture 6 — [Notes](/files/teaching/econometrics_graduate/lecture6/lecture6.html)

7. Lecture 7 - [Notes](/files/teaching/econometrics_graduate/lecture7_12/02-extremum-estimation-ja.html)

8. Lecture 8 - [Notes](/files/teaching/econometrics_graduate/lecture7_12/03-m-estimation-ja.html)

9. Lecture 9 - [Notes](/files/teaching/econometrics_graduate/lecture7_12/04-gmm-ja.html)

10. Lecture 10 - [Notes](/files/teaching/econometrics_graduate/lecture7_12/05-simulated-method-of-moments-ja.html)

11. Lecture 11 - [Notes](/files/teaching/econometrics_graduate/lecture7_12/06-minimum-distance-ja.html)

12. Lecture 12 - [Notes](/files/teaching/econometrics_graduate/lecture7_12/07-hypothesis-testing-ja.html)

ソースコードなどは [こちら](/files/teaching/econometrics_graduate/econome_grad_source.zip)

